# Generated by Django 5.1.1 on 2024-11-20 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name="product",
            old_name="name",
            new_name="product_name",
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="products.category",
            ),
            preserve_default=False,
        ),
    ]
