# Generated by Django 5.1.1 on 2024-10-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=15)),
                (
                    "service",
                    models.CharField(
                        choices=[
                            ("professional_makeup", "Professional Makeup"),
                            ("manicure_pedicure", "Manicure Pedicure"),
                            ("body_treatment", "Body Treatment"),
                            ("hair_treatment", "Hair Treatment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("message", models.TextField(blank=True, null=True)),
                ("booked_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
