# Generated by Django 5.1.1 on 2024-11-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0006_remove_order_status_remove_order_updated_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="total_price",
            new_name="amount",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="payment_status",
            new_name="status",
        ),
        migrations.AddField(
            model_name="order",
            name="razorpay_payment_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="razorpay_signature",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
