# Generated by Django 5.1.1 on 2024-11-14 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0007_rename_total_price_order_amount_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="product",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="user",
        ),
        migrations.RemoveField(
            model_name="order",
            name="user",
        ),
        migrations.DeleteModel(
            name="Product",
        ),
        migrations.DeleteModel(
            name="Cart",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
    ]
