# Generated by Django 5.1.1 on 2024-11-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0009_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(default="", upload_to="products"),
            preserve_default=False,
        ),
    ]
