# Generated by Django 5.1.1 on 2024-11-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0010_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="stock",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
