# Generated by Django 5.1.1 on 2024-11-15 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0014_alter_cart_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Cart",
        ),
    ]
