# Generated by Django 5.1.1 on 2024-11-19 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0015_delete_cart"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Product",
        ),
    ]
